# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
   echo Write your commands here
   
   mkdir "$(Build.BinariesDirectory)/raw-build"
   dir "$(Build.BinariesDirectory)/raw-build"
   set
   
   
   echo Use the environment variables input below to pass secret variables to this script
  displayName: 'Display Environment Info & Setup'

- script: |
   echo Write your commands here
   
   mkdir %AGENT_BUILDDIRECTORY%\d
   
   echo Use the environment variables input below to pass secret variables to this script
  displayName: 'Create Dependency Directory'

- task: DotNetCoreCLI@2
  displayName: 'Download AzureSignTool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install AzureSignTool --version 2.0.17 --tool-path $(Agent.BuildDirectory)\d'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
