# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
   echo Write your commands here
   
   mkdir "$(Build.BinariesDirectory)/raw-build"
   dir "$(Build.BinariesDirectory)/raw-build"
   set
   
   
   echo Use the environment variables input below to pass secret variables to this script
  displayName: 'Display Environment Info & Setup'

- script: |
   echo Write your commands here
   
   mkdir %AGENT_BUILDDIRECTORY%/d
   
   echo Use the environment variables input below to pass secret variables to this script
  displayName: 'Create Dependency Directory'

- task: DotNetCoreCLI@2
  displayName: 'Download AzureSignTool'
  inputs:
    command: custom
    custom: tool
    arguments: 'install AzureSignTool --version 2.0.17 --tool-path $(Agent.BuildDirectory)/d'

#Start: This should be in an include
- powershell: |
   # Write your powershell commands here.
   
   if (!(Test-Path "$(Agent.BuildDirectory)\d\"))
   {
       mkdir "$(Agent.BuildDirectory)\d\";
   }
   
   # Use the environment variables input below to pass secret variables to this script.
  displayName: 'Create Agent.BuildDirectory\d'

- bash: |
   # Write your commands here
   
   convert_path() {
     echo $(echo "/$1" | sed 's/\\/\//g' | sed 's/://' | sed -e 's/\(.*\)/\L\1/')
   }
   
   TOOL_PATH="$(echo $(convert_path '$(Agent.BuildDirectory)/d/NuGetKeyVaultSignTool.zip'))"
   
   echo $TOOL_PATH
   
   curl -o "$TOOL_PATH" "https://lndfbuild.blob.core.windows.net/utils/NuGetKeyVaultSignTool.zip"
   ls -l "$(Agent.BuildDirectory)/d"
   
   # Use the environment variables input below to pass secret variables to this script
  displayName: 'Download NuGetKeyVaultSignTool.zip'

- powershell: |
   # Write your powershell commands here.
   
   Expand-Archive -Path "$(Agent.BuildDirectory)/d/nugetkeyvaultsigntool.zip" -DestinationPath "$(Agent.BuildDirectory)/d/"
   
   # Use the environment variables input below to pass secret variables to this script.
  displayName: 'Unzip NuGetKeyVaultSignTool.zip into Agent.BuildDirectory/d'
#END: This should be in an include

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
