// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Landorphan.BuildMap.UnitTests.Specifications.MapFileCreation
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Map File Malformed Files")]
    [NUnit.Framework.CategoryAttribute("Check-In")]
    public partial class MapFileMalformedFilesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "Check-In"};
        
#line 1 "MapFileMalformedFiles.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Specifications/MapFileCreation", "Map File Malformed Files", "\tIn order to build complicated project structures\r\n\tAs a developer\r\n\tI want to to" +
                    " be able to create a mapping of all projects, their dependencies and their build" +
                    " order.", ProgrammingLanguage.CSharp, new string[] {
                        "Check-In"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Build a Simple Project")]
        public virtual void BuildASimpleProject()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Build a Simple Project", null, tagsOfScenario, argumentsOfScenario);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name",
                            "Language",
                            "Status"});
                table13.AddRow(new string[] {
                            "Project1",
                            "CSharp",
                            "Valid"});
                table13.AddRow(new string[] {
                            "Project2",
                            "CSharp",
                            "Malformed"});
#line 8
 testRunner.Given("I locate the following project files:", ((string)(null)), table13, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Name"});
                table14.AddRow(new string[] {
                            "Solution1"});
#line 12
      testRunner.And("I locate the following solution files:", ((string)(null)), table14, "And ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Solution",
                            "Project"});
                table15.AddRow(new string[] {
                            "Solution1",
                            "Project1"});
                table15.AddRow(new string[] {
                            "Solution1",
                            "Project2"});
#line 15
   testRunner.And("the following solutions contain the following located projects:", ((string)(null)), table15, "And ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Project",
                            "Reference"});
                table16.AddRow(new string[] {
                            "Project2",
                            "Project1"});
#line 19
   testRunner.And("the following projects contain the following references:", ((string)(null)), table16, "And ");
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Solution",
                            "Base Project",
                            "Dependent On"});
                table17.AddRow(new string[] {
                            "Solution1",
                            "Project2",
                            "Project1"});
#line 23
   testRunner.And("the following solutions define the following additional dependencies:", ((string)(null)), table17, "And ");
#line hidden
#line 26
      testRunner.And("the projects and solutions are saved on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 27
  testRunner.When("I create the map file with the following search patterns: **/*.sln", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Group",
                            "Item",
                            "Types",
                            "Language",
                            "Name",
                            "Status",
                            "Solutions",
                            "Id",
                            "Relative Path",
                            "Dependent On"});
                table18.AddRow(new string[] {
                            "0",
                            "0",
                            "Library",
                            "CSharp",
                            "Project1",
                            "Valid",
                            "Solution1",
                            "1",
                            "Project1`Project1.csproj",
                            ""});
                table18.AddRow(new string[] {
                            "-1",
                            "0",
                            "Library",
                            "CSharp",
                            "Project2",
                            "Malformed",
                            "Solution1",
                            "2",
                            "Project2`Project2.csproj",
                            ""});
#line 28
  testRunner.Then("the map file should contain the following projects:", ((string)(null)), table18, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
